services:
  app:
    container_name: taskmanager
    build: .
    ports:
      - 8080:8080
    environment:
      - DNS=postgres://postgres:password@db:5432/postgres?sslmode=disable
      - MIGRATE_PATH=migrations
    volumes:
      - ./migrations:/root/migrations
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432